# Changes here will be overwritten by Copier
_commit: v1.4.6
_src_path: https://github.com/lincc-frameworks/python-project-template.git
author_email: f.stoppa@astro.ru.nl
author_name: LSST ISSC
create_example_module: true
custom_install: true
include_benchmarks: false
include_docs: true
include_notebooks: true
mypy_type_checking: none
package_name: stamps_ad
preferred_linter: none
project_license: MIT
project_name: stamps-ad
project_organization: lsstissc
use_isort: false
